### ISSUE TITLE
Matrix too small

### ISSUE THREAD

**Issue by thuyvyng** [laurajjiang/capstone_ai_education#10]
On the Hub notebook the matrices are way too small, so we need to make the visualizations more responsive
![Screen Shot 2021-02-03 at 3 42 23 PM](https://user-images.githubusercontent.com/43559792/106978764-c577cd80-6711-11eb-9f70-7487db929280.png)

**Comment by MarkleyO** [comment]
I feel like at a certain point, with large datasets, the squares would have to be resized to extremely small portions to be able to fit the chart. Is there something else we should be doing here? (However we could for sure improve the scaling of squares)
